spring:
  profiles:
    active: local
    include:
    - local-url
    - dev-url
    - local-message
    - dev-message
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  config: classpath:logback/logback-spring.xml
