spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:13306/jpa
    username: caru
    password: rudeo512
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect